winget install discord.discord
winget install Google.Chrome
winget install Valve.Steam
winget install flow-launcher.flow-launcher
winget install Microsoft.VisualStudioCode
winget install 9PF4KZ2VN4W9
winget install git.git
winget install olivia.via
winget install RiotGames.LeagueOfLegends.NA
winget install nilesoft.shell
winget install python
winget install zoom.zoom
